### ISSUE TITLE
matrix subscript in tikzpicture

### ISSUE THREAD

**Issue by t-bltg** [cmhughes/latexindent.pl#85] opened 2017-09-01 11:21 UTC
I have an issue when using a subscript within a matrix block:

**sample.tex**
```tex
\documentclass[]{article}
\usepackage{tikz}
\usetikzlibrary{matrix}

\begin{document}
  \begin{tikzpicture}
    \matrix (A){
      c01 & c02 & c03 & c0q \\
      c_{11} & c12 & \ldots & c1q \\
    };
  \end{tikzpicture}

  \begin{tikzpicture}
    \matrix (A){
      c01 & c02 & c03 & c0q \\
      c11 & c12 & \ldots & c1q \\
    };
  \end{tikzpicture}
\end{document}
``` 

**output**
```tex
\documentclass[]{article}
\usepackage{tikz}
\usetikzlibrary{matrix}

\begin{document}
\begin{tikzpicture}
	\matrix (A){
		c01                           & c02 & c03    & c0q \\
		c_{11} & c12 & \ldots & c1q \\
	};
\end{tikzpicture}

\begin{tikzpicture}
	\matrix (A){
		c01 & c02 & c03    & c0q \\
		c11 & c12 & \ldots & c1q \\
	};
\end{tikzpicture}
\end{document}
```
Is there any special setting to use on that case ?

I use an un-modified latexindent from texlive release 2017 `latexindent.pl version 3.0.2`. The log shows only defaultSettings.yaml is used.

**Comment by cmhughes** [comment] 2017-09-01 17:39
Thanks very much for highlighting this; it is expected behaviour, but it's certainly not ideal. 

The reason for the behaviour is not the subscript, but the braces in `c_{11}`. This little string will be stored as a string (`LTXIN-TK-GROUPING-BRACES1-END` which you can see if you use `-t` and check the log file, `indent.log`) and will be used in the measuring of the columns in the ampersand alignment routine. 

If you upgrade to `Version 3.3` then you can use the following:
```
latexindent.pl  sample.tex -y="lookForAlignDelims:matrix:0"
```
which removes `matrix` from the alignment-at-ampersand routine, and indents the `matrix` command correctly (although the ampersands won't be aligned).

Alternatively, if you'd like to stick with your old version, then create `localSettings.yaml` with
```
lookForAlignDelims:
   matrix: 0
```
and run 
```
latexindent.pl  -l sample.tex
```
I'll add your example to the `known issues` section of the documentation; I'll leave this issue open as a reminder of something that I would like to try to resolve, although I can't be 100% sure that it is possible.

**Comment by cmhughes** [comment] 2017-09-01 17:40
PS: `texlive` 2017 should now have version 3.3, which should be updated automatically if you update `texlive`.

**Comment by neok-m4700** [comment] 2017-09-05 16:20
Thanks @cmhughes for the quick answer, I'll dig into latexindent when I'll have time to propose a fix.

**Comment by cmhughes** [comment] 2017-09-06 20:56
Some vague ideas about this:
- I think the solution may lie in `HiddenChildren.pm`;
- in particular, if a hidden child is found in an object that intends to align ampersands, then can we measure the total length of the hidden child's `begin`, `body` and `end` statement, and defer to this during the alignment routine?

**Comment by cmhughes** [comment] 2018-05-14 14:53
A few more vague ideas about this...

Referencing `Document.pm` we have
```
sub process_body_of_text{
    my $self = shift;

    # find objects recursively
    $logger->info('*Phase 1: searching for objects');
    $self->find_objects;

    # find all hidden child
    $logger->info('*Phase 2: finding surrounding indentation');
    $self->find_surrounding_indentation_for_children;

    # indentation recursively
    $logger->info('*Phase 3: indenting objects');
    $self->indent_children_recursively;

    # final indentation check
    $logger->info('*Phase 4: final indentation check');
    $self->final_indentation_check;

    return;
}
```
Perhaps during the `find_surrounding_indentation_for_children` we could do some measuring of a hidden child?

**Comment by cmhughes** [comment] 2018-05-19 10:02
For my own reference, this issue does *not* happen with, for example:
```
\begin{tabular}
              c01 & c02 & c03 & c0q \\
                    c_{11} & c12 & \ldots & c1q \\
\end{tabular}
```
This is because all of the entries of `tabular` are biological children of it. 

In 
```
\matrix (A){
              c01 & c02 & c03 & c0q \\
                    c_{11} & c12 & \ldots & c1q \\
	};
```
the entries are adopted children, and have *not* been processed at the time of alignment. 

This underlines that the answer will most likely lie within `HiddenChildren.pm`. Perhaps if the ancestor requires alignment, we take a measurement of the object and store the length during the family tree update?

**Comment by cmhughes** [comment] 2020-07-28 21:01
For my reference, see also https://github.com/cmhughes/latexindent.pl/issues/212

**Comment by cmhughes** [comment] 2021-03-06 11:06
For my reference, see also https://github.com/cmhughes/latexindent.pl/issues/251

**Comment by cmhughes** [comment] 2021-03-06 15:53
For my reference, see also https://github.com/cmhughes/latexindent.pl/issues/162

**Comment by cmhughes** [comment] 2021-06-26 08:32
I'm trying to work on this as a priority. It's intricate, but hopeful to take it forward. Updates to follow as I have them.

**Comment by cmhughes** [comment] 2021-07-23 12:54
Update! As of https://github.com/cmhughes/latexindent.pl/commit/d970ffaf0cbd8531bd787d3f54dc6d015849af82 the alignment routine has been upgraded, and now behaves a lot more like would be expected. I've demonstrated it with examples below. 

My apologies for the delay; I wouldn't usually expect to take this long to resolve an issue. This issue has been intricate, and required care, and the last few years have been quite intense. 

I have a few more things to check with this, but I'm hopeful to get a release out quite soon. I'll keep this open until it is released. Thanks for raising this :)

example: issue 85
-
from https://github.com/cmhughes/latexindent.pl/issues/85 starting with
```tex
\matrix {
c01 & c02 \\
c_{11} & c12 \\
}
```
gives, by default
```tex
\matrix {
	c01    & c02 \\
	c_{11} & c12 \\
}
```

example: issue 162
-
from https://github.com/cmhughes/latexindent.pl/issues/162 starting with
```tex
\begin{align}
A & =\begin{array}{cc}
BBB & CCC\\
E & F
\end{array}\\
Z & =\begin{array}{cc}
Y & X\\
W & V
\end{array}
\end{align}
```
gives, by default, 
```tex
\begin{align}
	A & =\begin{array}{cc}
		     BBB & CCC \\
		     E   & F
	     \end{array} \\
	Z & =\begin{array}{cc}
		     Y & X \\
		     W & V
	     \end{array}
\end{align}
```

example: issue 212
-
from https://github.com/cmhughes/latexindent.pl/issues/212 starting with 
```tex
\begin{equation}
    \begin{aligned}
        x =& x^2 \mqty[a_{11}  & a_{12} \\ a_{21} & a_{22}] =& f(x) \\
        y =& f(y) =& y^2 \\
        z =& f(z) =& z^2
    \end{aligned}
\end{equation}
```
gives, by default,
```tex
\begin{equation}
	\begin{aligned}
		x = & x^2 \mqty[a_{11} & a_{12} \\ a_{21} & a_{22}] =& f(x) \\
		y = & f(y) =           & y^2    \\
		z = & f(z) =           & z^2
	\end{aligned}
\end{equation}
```

example: issue 251
-
from https://github.com/cmhughes/latexindent.pl/issues/251 starting with
```tex
\begin{tabular}{ll}
  Testing & Line 1                        \\
  Testing & Line 2                        \\
  Testing & Line 3 \verb|X| \\
  Testing & Line 4                        \\
\end{tabular}
```
gives,  by default, 
```tex
\begin{tabular}{ll}
	Testing & Line 1          \\
	Testing & Line 2          \\
	Testing & Line 3 \verb|X| \\
	Testing & Line 4          \\
\end{tabular}
```

**Comment by t-bltg** [comment] 2021-07-23 12:57
Glad to hear that a fix is no the way :wink:

**Comment by cmhughes** [comment] 2021-07-23 12:58
And a big example from the source file of the documentation:
```tex
	\begin{longtable}{llll}
		\caption{Poly-switch mappings for all code-block types}\label{tab:poly-switch-mapping}                                                                                                                                                   \\
		\toprule
		Code block                                             & Sample                                                            & \multicolumn{2}{c}{Poly-switch mapping}                                                                     \\
		\midrule
		environment                                            & \verb!before words!$\BeginStartsOnOwnLine$                        & $\BeginStartsOnOwnLine$                 & BeginStartsOnOwnLine                                              \\
		                                                       & \verb!\begin{myenv}!$\BodyStartsOnOwnLine$                        & $\BodyStartsOnOwnLine$                  & BodyStartsOnOwnLine                                               \\
		                                                       & \verb!body of myenv!$\EndStartsOnOwnLine$                         & $\EndStartsOnOwnLine$                   & EndStartsOnOwnLine                                                \\
		                                                       & \verb!\end{myenv}!$\EndFinishesWithLineBreak$                     & $\EndFinishesWithLineBreak$             & EndFinishesWithLineBreak                                          \\
		                                                       & \verb!after words!                                                &                                         &                                                                   \\
		\cmidrule{2-4}
		ifelsefi                                               & \verb!before words!$\BeginStartsOnOwnLine$                        & $\BeginStartsOnOwnLine$                 & IfStartsOnOwnLine                                                 \\
		                                                       & \verb!\if...!$\BodyStartsOnOwnLine$                               & $\BodyStartsOnOwnLine$                  & BodyStartsOnOwnLine                                               \\
		                                                       & \verb!body of if/or statement!$\OrStartsOnOwnLine$                & $\OrStartsOnOwnLine$                    & OrStartsOnOwnLine                                                 %
		\announce{2018-04-27}{new ifElseFi code block poly-switches}                                                                                                                                                                             \\
		                                                       & \verb!\or!$\OrFinishesWithLineBreak$                              & $\OrFinishesWithLineBreak$              & OrFinishesWithLineBreak                                           \\
		                                                       & \verb!body of if/or statement!$\ElseStartsOnOwnLine$              & $\ElseStartsOnOwnLine$                  & ElseStartsOnOwnLine                                               \\
		                                                       & \verb!\else!$\ElseFinishesWithLineBreak$                          & $\ElseFinishesWithLineBreak$            & ElseFinishesWithLineBreak                                         \\
		                                                       & \verb!body of else statement!$\EndStartsOnOwnLine$                & $\EndStartsOnOwnLine$                   & FiStartsOnOwnLine                                                 \\
		                                                       & \verb!\fi!$\EndFinishesWithLineBreak$                             & $\EndFinishesWithLineBreak$             & FiFinishesWithLineBreak                                           \\
		                                                       & \verb!after words!                                                &                                         &                                                                   \\
		\cmidrule{2-4}
		optionalArguments                                      & \verb!...!$\BeginStartsOnOwnLine$                                 & $\BeginStartsOnOwnLine$                 & LSqBStartsOnOwnLine\footnote{LSqB stands for Left Square Bracket} \\
		                                                       & \verb![!$\BodyStartsOnOwnLine$                                    & $\BodyStartsOnOwnLine$                  & OptArgBodyStartsOnOwnLine                                         \\
		\announce{2019-07-13}{new comma-related poly-switches} & \verb!value before comma!$\ElseStartsOnOwnLine$,                  & $\ElseStartsOnOwnLine$                  & CommaStartsOnOwnLine                                              \\
		                                                       & $\ElseFinishesWithLineBreak$                                      & $\ElseFinishesWithLineBreak$            & CommaFinishesWithLineBreak                                        \\
		                                                       & \verb!end of body of opt arg!$\EndStartsOnOwnLine$                & $\EndStartsOnOwnLine$                   & RSqBStartsOnOwnLine                                               \\
		                                                       & \verb!]!$\EndFinishesWithLineBreak$                               & $\EndFinishesWithLineBreak$             & RSqBFinishesWithLineBreak                                         \\
		                                                       & \verb!...!                                                        &                                         &                                                                   \\
		\cmidrule{2-4}
		mandatoryArguments                                     & \verb!...!$\BeginStartsOnOwnLine$                                 & $\BeginStartsOnOwnLine$                 & LCuBStartsOnOwnLine\footnote{LCuB stands for Left Curly Brace}    \\
		                                                       & \verb!{!$\BodyStartsOnOwnLine$                                    & $\BodyStartsOnOwnLine$                  & MandArgBodyStartsOnOwnLine                                        \\
		\announce{2019-07-13}{new comma-related poly-switches} & \verb!value before comma!$\ElseStartsOnOwnLine$,                  & $\ElseStartsOnOwnLine$                  & CommaStartsOnOwnLine                                              \\
		                                                       & $\ElseFinishesWithLineBreak$                                      & $\ElseFinishesWithLineBreak$            & CommaFinishesWithLineBreak                                        \\
		                                                       & \verb!end of body of mand arg!$\EndStartsOnOwnLine$               & $\EndStartsOnOwnLine$                   & RCuBStartsOnOwnLine                                               \\
		                                                       & \verb!}!$\EndFinishesWithLineBreak$                               & $\EndFinishesWithLineBreak$             & RCuBFinishesWithLineBreak                                         \\
		                                                       & \verb!...!                                                        &                                         &                                                                   \\
		\cmidrule{2-4}
		commands                                               & \verb!before words!$\BeginStartsOnOwnLine$                        & $\BeginStartsOnOwnLine$                 & CommandStartsOnOwnLine                                            \\
		                                                       & \verb!\mycommand!$\BodyStartsOnOwnLine$                           & $\BodyStartsOnOwnLine$                  & CommandNameFinishesWithLineBreak                                  \\
		                                                       & $\langle$\itshape{arguments}$\rangle$                             &                                         &                                                                   \\
		\cmidrule{2-4}
		namedGroupingBraces Brackets                           & before words$\BeginStartsOnOwnLine$                               & $\BeginStartsOnOwnLine$                 & NameStartsOnOwnLine                                               \\
		                                                       & myname$\BodyStartsOnOwnLine$                                      & $\BodyStartsOnOwnLine$                  & NameFinishesWithLineBreak                                         \\
		                                                       & $\langle$\itshape{braces/brackets}$\rangle$                       &                                         &                                                                   \\
		\cmidrule{2-4}
		keyEqualsValuesBraces\newline Brackets                 & before words$\BeginStartsOnOwnLine$                               & $\BeginStartsOnOwnLine$                 & KeyStartsOnOwnLine                                                \\
		                                                       & key$\EqualsStartsOnOwnLine$=$\BodyStartsOnOwnLine$                & $\EqualsStartsOnOwnLine$                & EqualsStartsOnOwnLine                                             \\
		                                                       & $\langle$\itshape{braces/brackets}$\rangle$                       & $\BodyStartsOnOwnLine$                  & EqualsFinishesWithLineBreak                                       \\
		\cmidrule{2-4}
		items                                                  & before words$\BeginStartsOnOwnLine$                               & $\BeginStartsOnOwnLine$                 & ItemStartsOnOwnLine                                               \\
		                                                       & \verb!\item!$\BodyStartsOnOwnLine$                                & $\BodyStartsOnOwnLine$                  & ItemFinishesWithLineBreak                                         \\
		                                                       & \verb!...!                                                        &                                         &                                                                   \\
		\cmidrule{2-4}
		specialBeginEnd                                        & before words$\BeginStartsOnOwnLine$                               & $\BeginStartsOnOwnLine$                 & SpecialBeginStartsOnOwnLine                                       \\
		                                                       & \verb!\[!$\BodyStartsOnOwnLine$                                   & $\BodyStartsOnOwnLine$                  & SpecialBodyStartsOnOwnLine                                        \\
		                                                       & \verb!body of special/middle!$\ElseStartsOnOwnLine$               & $\ElseStartsOnOwnLine$                  & SpecialMiddleStartsOnOwnLine                                      %
		\announce{2018-04-27}{new special code block poly-switches}                                                                                                                                                                              \\
		                                                       & \verb!\middle!$\ElseFinishesWithLineBreak$                        & $\ElseFinishesWithLineBreak$            & SpecialMiddleFinishesWithLineBreak                                \\
		                                                       & body of special/middle $\EndStartsOnOwnLine$                      & $\EndStartsOnOwnLine$                   & SpecialEndStartsOnOwnLine                                         \\
		                                                       & \verb!\]!$\EndFinishesWithLineBreak$                              & $\EndFinishesWithLineBreak$             & SpecialEndFinishesWithLineBreak                                   \\
		                                                       & after words                                                       &                                         &                                                                   \\
		\cmidrule{2-4}
		verbatim                                               & before words$\BeginStartsOnOwnLine$\verb!\begin{verbatim}!        & $\BeginStartsOnOwnLine$                 & VerbatimBeginStartsOnOwnLine                                      \\
		\announce{2019-05-05}{verbatim poly-switches}          & body of verbatim \verb!\end{verbatim}!$\EndFinishesWithLineBreak$ & $\EndFinishesWithLineBreak$             & VerbatimEndFinishesWithLineBreak                                  \\
		                                                       & after words                                                       &                                         &                                                                   \\
		\bottomrule
	\end{longtable}
```

**Comment by cmhughes** [comment] 2021-07-23 15:35
Released as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.10.1, uploaded to ctan, you should be able to get it using your TeX distribution manager within about 24 hours, ctan allowing.

**Closed by cmhughes** 2021-07-23 15:35 UTC
Labels: align-at-ampersand-routine, expected-behaviour, implemented
