### ISSUE TITLE
Run without Unicode::GCString ?

### ISSUE THREAD

**Issue by tdegeus** [cmhughes/latexindent.pl#303] opened 2021-11-13 07:34 UTC
I have been preparing a conda feedstock for this library : https://github.com/conda-forge/staged-recipes/pull/16914

A problem that appeared, and that might persist for a while, stems from the fact that Unicode::GCString wraps a compiled library (sombok). Now the issue is that there is currently no way yes to ship the binary for mac's ARM processor (at least not on conda-forge as it currently relies on cross-compilation as Azure does not have (sufficient) hardware yet).

So now the question: is there a way to run without Unicode::GCString (e.g. in a "light" mode) ? Or is there a way to run without the compile sombok library ?

**Comment by cmhughes** [comment] 2021-11-13 08:25
Thanks for this.

The GCString module is central to the align at ampersand routine.

It is not possible to run the script without it.

Is it possible to create a standalone executable file for Mac that wouldn't require perl?

**Comment by cmhughes** [comment] 2021-11-13 08:43
I should have said: thank you for taking this forward, and for contributing to the project. I really appreciate it :)

**Comment by cmhughes** [comment] 2021-11-13 08:47
In case it's helpful, here's a link to the github action that creates the Windows executable:

https://github.com/cmhughes/latexindent.pl/actions/runs/1454209891/workflow

Perhaps something similar could be done to create a Mac executable that doesn't need perl....?

**Comment by tdegeus** [comment] 2021-11-13 11:09
I think for sure it should be done on Windows!
 
Then, not sure if it solves the Mac ARM issue, as the problem is that for now it is cross-compiled, so probably we would hit the same issue.

**Comment by cmhughes** [comment] 2021-11-16 15:58
Is there anything I can do to progress this?

**Comment by cmhughes** [comment] 2021-11-16 18:24
Thanks, that's helpful.I'm going to note the following here for possible exploration:

https://stackoverflow.com/questions/1326539/how-do-i-find-the-length-of-a-unicode-string-in-perl

https://perldoc.perl.org/perlunicook

If you, or anyone else, feels like exploring, the main file to focus upon is AlignAtAmpersand.pm.

**Comment by tdegeus** [comment] 2021-11-16 21:00
Sounds interesting. My perl expertise is not enough to contribute with such a change in finite time. However, I would strongly encourage a perl-only solution. This would render `latexindent.pl` more robust and completely OS and hardware independent

**Comment by cmhughes** [comment] 2021-12-02 17:26
Some encouraging early tests...
```perl
use Encode;
my @unicodetests = ("brûlée","Jörg","Größe");
for(@unicodetests){
    print length(Encode::decode('UTF-8', $_)),"\n";
}
```
gives
```
6
4
5
```
as expected... further experimentation needed.

**Comment by tdegeus** [comment] 2021-12-02 17:35
Sounds great. Starting preparations : https://github.com/conda-forge/staged-recipes/pull/17143

**Comment by tdegeus** [comment] 2021-12-02 18:03
@cmhughes Not sure is Encode solves the problem we set out to solve : https://github.com/dankogai/p5-encode/issues/163 .

**Comment by cmhughes** [comment] 2021-12-02 18:12
OK!

The bottom line is: latexindent needs a way to measure Unicode strings.

**Comment by tdegeus** [comment] 2021-12-02 18:18
@cmhughes Seems that I misjudged: Encode is part of perl's core, which we do have on all platforms, so using it should solve all problems. Indeed I can simply run your example

**Comment by tdegeus** [comment] 2021-12-02 18:21
(Regardless of the issue with which this started: it seems much safer to depend on a core library, Unicode::GCString does not seem to be too actively maintained)

**Comment by cmhughes** [comment] 2021-12-02 18:35
OK, that's good to know :)

I'll continue to explore. The above was a good first step :) updates to
follow when I have them.

**Comment by cmhughes** [comment] 2021-12-04 18:09
As of https://github.com/cmhughes/latexindent.pl/commit/ebdcbd903dfde66e8084c9321d5621fc246e882e I believe this is implemented. 

Feel free to grab a copy of the `develop` branch if you'd like to test it. I'm hoping to get a new version released soon.

**Comment by cmhughes** [comment] 2021-12-05 08:26
To test:

https://www.cl.cam.ac.uk/~mgk25/ucs/examples/quickbrown.txt

(i searched for 'unicode test string')

**Comment by tdegeus** [comment] 2021-12-05 09:21
I can confirm that latexindent.pl works as expected on my document ! So without perl-unicode-linebreak such that it is now fully hardware independent. Thanks a lot !! 

The conda-forge package will update with the new release.

**Comment by tdegeus** [comment] 2021-12-05 09:28
https://github.com/conda-forge/latexindent.pl-feedstock/pull/1

**Comment by cmhughes** [comment] 2021-12-05 10:40
That's great, that ks for confirming.

Thanks also for your contribution to the README.

Do you think the appendix in the documentation could use some details too? If so, feel free to submit another pull request, or to give me something that I can copy & paste into it.

https://latexindentpl.readthedocs.io/en/latest/appendices.html

**Comment by tdegeus** [comment] 2021-12-05 11:13
Done : https://github.com/cmhughes/latexindent.pl/pull/311

**Comment by cmhughes** [comment] 2021-12-05 20:18
A few test cases are causing issues. I'm working on resolving them, which is delaying the release.... details to follow when I have them.

**Comment by cmhughes** [comment] 2021-12-13 17:11
Work will continue on this, but on its own branch https://github.com/cmhughes/latexindent.pl/commit/3044ed32f6c927ccd3c6745ba1c52d1274517dc0

I'm hoping to pick this up in the new year.

**Comment by tdegeus** [comment] 2021-12-13 17:29
Just to make sure with what you mean "on its own branch" : I guess that you mean still needing some things like additional unit-tests etc. before merging ? Or do you intend to keep it on a separate branch?

**Comment by cmhughes** [comment] 2021-12-13 17:31
The first thing:I need to do more testing.

I think it'll be fine, but I need to dedicate some time to it.

I hope to take it on in 2022.

**Comment by tdegeus** [comment] 2022-01-19 09:06
Just a side note, not to pressure you (well ok a little ;)). Using the `Makefile.PL` we are writing in https://github.com/cmhughes/latexindent.pl/issues/316 I finally also tested if CPAN *does* provide a macOS ARM package for `Unicode::GCString`, and the answer is *no*. 

Likewise I finally tested for `texlive` distribution: same answer.

So on this platform that dependency is really a blocker with the only possible solution hand-compiling the dependency

**Comment by cmhughes** [comment] 2022-01-19 09:17
Great, many thanks.

I'm hoping to test this more over the coming days. I'm compiling some more
questions, which will follow :)

The GCString thing is going to have to wait until this has been finished.
Changing that could, if not done carefully, fundamentally break the script,
it can't be rushed.

Let's stay focused on this as is, it's going in a nice direction :)

**Comment by cmhughes** [comment] 2022-01-19 09:19
This response was designed for the pull request, apologies.

**Comment by paddyroddy** [comment] 2022-01-25 15:12
This library is great and very glad there's an official `pre-commit` hook now but I am now running into issues with `Unicode::GCString` mentioned above on M1 arm mac.

I can't explain why but my M1 (non-pro) mac is able to run it, not sure how I got it to work. But my brand new M1 Pro/max one cannot due to `Unicode::GCStirng`. The error I descirbed here https://github.com/Perl/perl5/issues/19367

**Comment by tdegeus** [comment] 2022-01-25 15:16
It's simply because `Unicode::GCString` is a compile module that is not provided for your (and mine) hardware. I've patched the [conda package](https://github.com/conda-forge/latexindent.pl-feedstock) with the fix discussed here, so that you can use without any problem

**Comment by khwilliamson** [comment] 2022-01-25 16:03
I looked up what sombok does.  From its README, it appears that it could be replaced by features in modern Perl.  \X matches a single grapheme since v5.8.  \b{gcb} is another way of looking at that information. \b{lb} can be used to easily implement the Unicode line breaking algorithm.  Both the \b{} constructs were introduced in Perl 5.22.  In other words, there likely is a pure perl solution to sombok since that time

**Comment by paddyroddy** [comment] 2022-01-25 16:51
> It's simply because `Unicode::GCString` is a compiled module that is not provided for your (and mine) hardware. I've patched the [conda package](https://github.com/conda-forge/latexindent.pl-feedstock) with the fix discussed here, so that you can use without any problem.
> 
> Alternatively you could manually compile `Unicode::GCString` on your system.

How do I compile `Unicode::GCString` manually?

**Comment by tdegeus** [comment] 2022-01-25 16:53
(No guarantee, I'm not an expert)

I think that you can do this locally 
```bash
perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
make
make test
make install VERBINST=1
```

Reference:
https://github.com/conda-forge/perl-unicode-linebreak-feedstock/blob/561a8c44b5a006858dbfeafaf983e6e32b427022/recipe/meta.yaml#L18

**Comment by paddyroddy** [comment] 2022-01-25 17:08
> (No guarantee, I'm not an expert)
> 
> I think that you can do this locally
> 
> ```shell
> perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
> make
> make test
> make install VERBINST=1
> ```
> 
> Reference: https://github.com/conda-forge/perl-unicode-linebreak-feedstock/blob/561a8c44b5a006858dbfeafaf983e6e32b427022/recipe/meta.yaml#L18

gave it a go, no luck

**Comment by cmhughes** [comment] 2022-03-16 15:16
I need to explore the following https://stackoverflow.com/questions/3945583/how-can-i-conditionally-use-a-module-in-perl

**Comment by tdegeus** [comment] 2022-03-16 16:17
(For info, I have been using the feature/no-GCstring path for a while now without any problems. There were also no complaints on the conda feedstock that has been using this patch since the beginning)

**Comment by cmhughes** [comment] 2022-03-20 07:48
Some progress on this, I think :) https://github.com/cmhughes/latexindent.pl/commit/0b8f7b916e73d069fe9ac25056007fd1f78c3d13 still on its own branch, for the moment.

I'm not sure if you can test the following perl script, @tdegeus ...? In particular, I'd like to know what the following calls give you:
```
perl test-gcstring-load.pl
perl test-gcstring-load.pl --GCString
```
I'd hope that the *first* one works, and that the second one does *not* work (because you don't have `Unicode::GCString` installed/available).

test-gcstring-load.pl
-
```perl
use strict;
use warnings;
use Getopt::Long;

# get the options
my %switches = ();

GetOptions (
    "GCString"=>\$switches{GCString},
);

# conditionally load the GCString module
eval "use Unicode::GCString" if $switches{GCString};

if ($switches{GCString}){
    print "GCString *is* loaded\n";
} else {
    print "GCString is *not* loaded\n";
}
exit (0);
```

**Comment by tdegeus** [comment] 2022-03-21 13:08
Furthermore,
```perl
use if 0, "Unicode::GCString";  # -> runs without error
use if 1, "Unicode::GCString";  # -> throws with "Can't locate Unicode/GCString.pm in @INC"
use if $switches{GCString}, "Unicode::GCString";  # -> runs without errors regardless of the command line argument (even though the correct string is printed)
```

**Comment by tdegeus** [comment] 2022-03-21 13:17
When I try to run `latexindent.pl` from the `feature/no-GCString` branch
```
/my/path/latexindent.pl -l -m -s -w main.tex
```
runs successfully, while 
```
/my/path/latexindent.pl -l -m -s -w --GCString main.tex
```
throws with 
```
Can't locate object method "new" via package "Unicode::GCString" (perhaps you forgot to load "Unicode::GCString"?) at /my/path/latexindent.pl/LatexIndent/AlignmentAtAmpersand.pm line 1595
```

**Comment by cmhughes** [comment] 2022-03-21 16:18
Great, thanks for your time on this!

I think that everything you report is as expected (which isn't what I originally thought).

The `eval` statement is called at 'run' time, I think, whereas the `use` statement is called at 'compile' time. 

The script can continue even if the Eval statement fails.

The script can not continue if the use statement fails.

I'll get this documented and hopefully merged and then released :)

**Comment by tdegeus** [comment] 2022-03-21 16:20
Awesome! Looking forward to it!

**Comment by cmhughes** [comment] 2022-03-25 16:20
This is implemented and documented as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.17

This *should* mean that you no longer need the `feature/no-GCString` branch. Let me know once you no longer need it, and I'll delete it. Thanks for your help!

**Closed by cmhughes** 2022-03-25 16:20 UTC
Labels: implemented, internal, feature-request, align-at-ampersand-routine

**Comment by tdegeus** [comment] 2022-03-25 17:13
Works like a charm, thanks a million 🙏

**Comment by cmhughes** [comment] 2022-03-25 17:25
Great to hear. I'll plan to delete the feature branch.

**Comment by cmhughes** [comment] 2022-04-02 08:06
`feature/no-GCString` deleted :)
