### ISSUE TITLE
Configuring defaultSettings using null-ls

### ISSUE THREAD

**Issue by 777uliahshafar** [cmhughes/latexindent.pl#457] opened 2023-07-26 09:25 UTC
Hello, I am using your plugin with null-ls for formatting my latex file. However, I'd like to modify configuration such as don't line break a paragraph. Could you address this out, Mr. Thank you.

**Comment by cmhughes** [comment] 2023-07-26 10:48
Please use the issue template and I'll try to help.

**Comment by cmhughes** [comment] 2023-07-26 13:53
Duplicate of https://github.com/cmhughes/latexindent.pl/issues/458

**Closed by cmhughes** 2023-07-26 13:53 UTC
