### ISSUE TITLE
Misaligned “\\" after "\verb|...|" in tabular environments

### ISSUE THREAD

**Issue by salutis** [cmhughes/latexindent.pl#251] opened 2021-03-06 10:57 UTC
# `.tex` code

```
\begin{tabular}{ll}
  Testing & Line 1                        \\
  Testing & Line 2                        \\
  Testing & Line 3 \verb|X| \\
  Testing & Line 4                        \\
\end{tabular}
```
# `yaml` settings

```
salutis@Workstation ~ % cat ~/.indentconfig.yaml
paths:
- /Users/salutis/.indentconfig.yaml

# The following value should match |tabstop| in |~/.vimrc|.
defaultIndent: "  "
```

# Desired or expected output

I expect all the `\\` to line up vertically, including the one after `\verb|X|`.

**Comment by cmhughes** [comment] 2021-03-06 11:05
Thanks. 

Yes, this output is expected, and I appreciate that it is not ideal.

The reasoning is that the `\verb|X|` command will be replaced with a token, the indentation and alignment is done, and then the verbatim token will be replaced with its value. The unfortunate thing is that the token used is longer than the string that it represents. 

This is a known issue, and this behaviour is expected. I would say that this issue is a duplicate of https://github.com/cmhughes/latexindent.pl/issues/85 

I'm exploring a new approach which I hope might assist with this behaviour. Details will follow as and when I have them. 

For the moment, I will reference this issue within https://github.com/cmhughes/latexindent.pl/issues/85 so that I have it for reference.

Thanks again.

**Closed by cmhughes** 2021-03-06 11:05 UTC

**Comment by cmhughes** [comment] 2021-07-23 12:54
Update! see https://github.com/cmhughes/latexindent.pl/issues/85 :) release to follow soon :)

**Comment by cmhughes** [comment] 2021-07-23 15:36
Released as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.10.1, uploaded to ctan, you should be able to get it using your TeX distribution manager within about 24 hours, ctan allowing.
