### ISSUE TITLE
Missing space in columns with umlauts in UTF-8

### ISSUE THREAD

**Issue by fixxl** [cmhughes/latexindent.pl#55] opened 2017-02-22 13:14 UTC
I noticed that when formatting a tabular in a UTF-8-document with latexindent the "&" are not aligned correctly if some columns contain text with umlauts (ä, ö, ü, ß) and some don't. In columns with umlauts there's always one space missing per umlaut as if latexident interprets umlauts as two letters.

If I switch the document encoding to ISO-8859-1 and run latexident, everything is aligned perfectly.

**Comment by cmhughes** [comment] 2017-02-22 19:58
Thanks very much for reporting this issue! 

It would be really helpful if you could provide a small, complete minimum working example for me to work with; in particular, it would be great if you could provide the output you receive, and the output that you would *expect* to receive. 

Best wishes
Chris

**Comment by fixxl** [comment] 2017-02-23 14:10
Sorry for the sloppy description, I try to be a bit more accurate.

This is my MWE without any alignment and indentation:
[indentexample-raw.tex.txt](https://github.com/cmhughes/latexindent.pl/files/796620/indentexample-raw.tex.txt)

This is the result when I run latexindent with font encoding set to UTF-8 (no proper alignment):
[indentexample-indent-utf8.tex.txt](https://github.com/cmhughes/latexindent.pl/files/796622/indentexample-indent-utf8.tex.txt)

And this is the result when I run latexindent with font encoding set to ISO-8859-1 (that's what I want it to look like):
[indentexample-indent-iso-8859-1.tex.txt](https://github.com/cmhughes/latexindent.pl/files/796621/indentexample-indent-iso-8859-1.tex.txt)

**Comment by cmhughes** [comment] 2017-02-23 17:30
Thanks very much for the follow-up, this is very helpful.

Could you expand a bit more on the details of how you set font encoding to ISO-8859-1. If you have suggestions on the changes that I should make (ideally with references for me to take a look at), I'd be most grateful! :)

Thanks again
Chris

**Comment by fixxl** [comment] 2017-02-23 19:34
There's a switch at the bottom of the screen in TeXstudio to switch the type of encoding.

The problem really seems to be that UTF-8 is not restricted to a single byte per character: http://stackoverflow.com/questions/7048745/what-is-the-difference-between-utf-8-and-iso-8859-1 . Thus latexindent interprets two bytes that form the umlaut as two characters and therefore omits a whitespace for every umlaut.

**Comment by cmhughes** [comment] 2017-02-23 22:09
Ok, thanks for this; there are a few issues to resolve ahead of this one, but I will investigate and get back to you if I have questions.

**Comment by cmhughes** [comment] 2017-03-12 08:36
Sorry for the delay :) 

Yes, it's definitely a bug, and not intended behaviour -- thanks for reporting this. I've labelled it as a bug, and will hope to address it in the next development push. I'm still taking a little break from development following the monster effort to build v3.0, but your issue is on the list! Of course, if you'd like to have a go at fixing it yourself and submitting a patch, do feel free :)

Thanks again
Chris

**Comment by cmhughes** [comment] 2017-03-15 18:13
Could be helpful:

http://stackoverflow.com/questions/1326539/how-do-i-find-the-length-of-a-unicode-string-in-perl

**Comment by cmhughes** [comment] 2017-04-20 09:48
First implementation of this in https://github.com/cmhughes/latexindent.pl/commit/7215f268f3c6d722af26f5acda4f19d51766b867

This implementation uses the `Text::CharWidth` module; other references suggest other approaches, for example see http://www.perl.com/pub/2012/05/perlunicook-string-length-in-graphemes.html, http://www.perl.com/pub/2012/05/perlunicook-unicode-column-width-for-printing.html, http://stackoverflow.com/questions/2064543/how-can-i-properly-align-utf-8-strings-with-perls-printf. 

In particular, as @tchrist recommends `Unicode::GCString`, I should probably aim for it. Will investigate further.

**Comment by cmhughes** [comment] 2017-04-29 15:45
New implementation of this as of: https://github.com/cmhughes/latexindent.pl/commit/b305c4402b0b436289200240fda5a3141f25e8e0

This raised a question when creating the Windows executable file: http://stackoverflow.com/questions/43549240/perl-par-packer-executable-with-unicodegcstring-cant-locate-object-method/43690984#43690984 which was fixed using the solution given in the answer. 

Explicitly, I created ppp.pl
```
$ENV{PAR_VERBATIM}=1;
system 'pp', @ARGV;
```
and then ran:
```
perl ppp.pl -u -o latexindent.exe latexindent.pl
```

**Comment by cmhughes** [comment] 2017-04-29 16:04
This has been fixed as of https://github.com/cmhughes/latexindent.pl/pull/61

I've uploaded v3.0.1 to ctan, 29th April, 2017, 17.00 GMT.

Thanks a lot for reporting this bug, and helping to drive the project forward!

**Closed by cmhughes** 2017-04-29 16:04 UTC
Labels: bug, implemented
