### ISSUE TITLE
Incorrect column breaking when using `multiColumnGrouping`

### ISSUE THREAD

**Issue by qiancy98** [cmhughes/latexindent.pl#301] opened 2021-11-09 07:06 UTC
Please provide the following when posting an issue:

original .tex code
--
```LaTeX
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\[
\begin{array}{ccc*{19}{c@{}}cr}
	n & r & k & \multicolumn{20}{l}{\operatorname{DT}(n+1,r+1,k)}   & \# (n-r) \text{-LEO}  \\
	\hline
	2           & 2           & 1  & +& & & & & & & & & & & & & & & & & & &  & 24          \\
\end{array}
\]
\end{document}
```

yaml settings
--
*Please paste your YAML settings (if any) here*

actual/given output
--
```LaTeX
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\[
	\begin{array}{ccc*{19}{c@{}}cr}
		n & r & k & \multicolumn{20}{l}{\operatorname{DT}(n+1,r+1,k)} & \# (n-r) \text{-LEO}                                     \\
		2 & 2 & 1 & + &                                               &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  & 24 \\
	\end{array}
\]
\end{document}
```
desired or expected output
--
```LaTeX
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\[
	\begin{array}{ccc*{19}{c@{}}cr}
		n & r & k & \multicolumn{20}{l}{\operatorname{DT}(n+1,r+1,k)}          & \# (n-r) \text{-LEO} \\
		2 & 2 & 1 & + &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  & 24                   \\
	\end{array}
\]
\end{document}
```
anything else
--
We should use `#1` in `\multicolumn#1` for the columns it occupies, instead of the fixed number `2`.

**Comment by cmhughes** [comment] 2021-11-09 09:18
Please see https://latexindentpl.readthedocs.io/en/latest/sec-default-user-local.html#lst-tabular2yaml

You will need to specify it for the array environment.

**Comment by qiancy98** [comment] 2021-11-09 09:24
I use the yaml setting
```yaml
lookForAlignDelims:
   tabular: 
      multiColumnGrouping: 1
```
but I forgot to put it here.
I mean, when we turn on this switch, we view `\multicolumn#1#2#3` as two columns, but I think we should view it as `#1` columns.
For this example, it is `20`.

**Comment by cmhughes** [comment] 2021-11-09 10:41
Your example uses an array, so your yaml needs to use array.

**Comment by cmhughes** [comment] 2021-11-09 10:44
> I mean, when we turn on this switch, we view \multicolumn#1#2#3 as two columns,

That's not correct. 

> but I think we should view it as #1 columns.

This already happens.

**Comment by qiancy98** [comment] 2021-11-10 03:33
File example1.tex
```LaTeX
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\[
\begin{array}{ccc*{19}{c@{}}cr}
	n & r & k & \multicolumn{20}{l}{\operatorname{DT}(n+1,r+1,k)}   & \# (n-r) \text{-LEO}  \\
	\hline
	2           & 2           & 1  & +& & & & & & & & & & & & & & & & & & &  & 24          \\
\end{array}
\]
\end{document}
```
File example1.yaml (I have committed all lines of `indentconfig.yaml`.)
```yaml
lookForAlignDelims:
   array: 
      multiColumnGrouping: 1
```
powershell command:`latexindent .\example1.tex -l .\example1.yaml -o .\example1.out`
File example1.out.tex
```LaTeX
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\[
	\begin{array}{ccc*{19}{c@{}}cr}
		n & r & k & \multicolumn{20}{l}{\operatorname{DT}(n+1,r+1,k)} & \# (n-r) \text{-LEO}                                     \\
		\hline
		2 & 2 & 1 & + &                                               &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  & 24 \\
	\end{array}
\]
\end{document}
```
It is not desired.


---
Sorry I forget the changing of `indentconfig.yaml`, resulting the difficulty in testing. This time it should be OK.

**Comment by cmhughes** [comment] 2021-11-10 08:55
I can confirm the results you describe. This is not intended behaviour. I'll look into it, thanks for reporting!

**Comment by cmhughes** [comment] 2022-01-08 16:51
This is fixed as of https://github.com/cmhughes/latexindent.pl/commit/54438d66e9232a5c8ff249a788f463e18ef2f536. It'll be part of the next release. 

I'll keep this issue open until the release.

Thanks for reporting!

**Comment by cmhughes** [comment] 2022-01-08 18:57
resolved as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.14 upload to ctan imminent.

**Closed by cmhughes** 2022-01-08 18:57 UTC
Labels: bug, implemented, align-at-ampersand-routine
