### ISSUE TITLE
Option for NOT to align the tailing "\\"

### ISSUE THREAD

**Issue by zhi-wang** [cmhughes/latexindent.pl#46] opened 2016-06-13 23:25 UTC
Hi Chris, your tool is GREAT! It is the cure for the people like me with minor obsessions. But is possible to add an option in the settings that make it NOT to align the tailing "\\\\"? E.g. if I had this long equation

A = BBBB + CCCC &+ DDD \\\\
                                &+ EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE \\\\
                                &+ FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

latexindent always seemed to insert a lot of white space between DDD and "\\\\" which actually didn't help if this line was super-long and the text editor was set to the "wrap" mode.

Or is it already there that I just haven't found it?

**Comment by cmhughes** [comment] 2016-06-14 19:18
Hello Zhi-wang!
Thanks very much for your kind words, I'm glad that you like the tool :)

I believe that the issue you described was detailed here: https://github.com/cmhughes/latexindent.pl/issues/26 As such, you'll see that the develop branch (https://github.com/cmhughes/latexindent.pl/tree/develop) has it implemented, so if you pull from it, you should be able to use the feature.

I'm currently working on a completely new implementation (see https://github.com/cmhughes/latexindent.pl/tree/object-oriented-approach). All of the old features (including the one detailed above) will be available, together with quite a few more (related to modifying line breaks), but development is slow as I can only work on it in my 'spare' time :)

Hope this helps; let me know if your issue is indeed a duplicate of the one detailed above.
Best
Chris

**Comment by zhi-wang** [comment] 2016-06-14 19:29
Yes #26 is exactly what I asked! Thank you for your reply.

**Closed** 2016-06-14 20:44 UTC
Labels: duplicate, question
