### ISSUE TITLE
tabularray's cmidrule causes the conflict between "modifyLineBreaks" and "lookForAlignDelims"

### ISSUE THREAD

**Issue by tatsy** [cmhughes/latexindent.pl#426] opened 2023-03-04 04:50 UTC
It seems that when I use `\cmidrule` command in `tblr` environment (of `tabularray`), the "lookForAlignDelims" does not work properly due to the conflict with "modifyLineBreaks".

I got the following output with the command:
```shell
latexindent main.tex -l -m -r
```

The versions of Perl and latexindent in my environment are:
- Perl: v5.36.0
- latexindent: 3.20.1, 2023-01-07

Thank you in advance for your kind assistance.

original .tex code
--

```latex
\documentclass[10pt]{article}

\usepackage{tabularray}
\UseTblrLibrary{booktabs}

\begin{document}

\title{Hello}
\author{Hello}

\maketitle

\section{Table}

Hello world!
Hello world!

\begin{table}[t]
  \begin{tblr}{colspec={Q[c]Q[c]Q[c]Q[c]}}
    \toprule
    aaaaaa & bbbbb & ccc & dd \\
    \cmidrule[r]{1-1} \cmidrule{2-4}
    11 & 2 & 33 & 4 \\
    5 & 66 & 7 & 8 \\
    \bottomrule
  \end{tblr}
\end{table}

\end{document}
```

yaml settings
--
```yaml
onlyOneBackup: 1
defaultIndent: "  "
removeTrailingWhiteSpace: 1

modifyLineBreaks:
  textWrapOptions:
    columns: 9999
    condenseMultipleBlankLinesInto: 1

lookForAlignDelims:
  tblr:
    delim: 1
    dontMeasure: largest
```

actual/given output
--
```latex
\documentclass[10pt]{article}

\usepackage{tabularray}
\UseTblrLibrary{booktabs}

\begin{document}

\title{Hello}
\author{Hello}

\maketitle

\section{Table}

Hello world! Hello world!

\begin{table}[t]
  \begin{tblr}{colspec={Q[c]Q[c]Q[c]Q[c]}}
    \toprule
    aaaaaa & bbbbb & ccc & dd \\
    \cmidrule[r]{1-1} \cmidrule{2-4}
    11 & 2 & 33 & 4          \\
    5  & 66 & 7  & 8          \\
    \bottomrule
  \end{tblr}
\end{table}

\end{document}
```

desired or expected output
--

```latex
\documentclass[10pt]{article}

\usepackage{tabularray}
\UseTblrLibrary{booktabs}

\begin{document}

\title{Hello}
\author{Hello}

\maketitle

\section{Table}

Hello world! Hello world!

\begin{table}[t]
  \begin{tblr}{colspec={Q[c]Q[c]Q[c]Q[c]}}
    \toprule
    aaaaaa & bbbbb & ccc & dd \\
    \cmidrule[r]{1-1} \cmidrule{2-4}
    11 & 2  & 33 & 4          \\
    5  & 66 & 7  & 8          \\
    \bottomrule
  \end{tblr}
\end{table}

\end{document}
```

anything else
--

When I remove `\cmidrule` from the above code, I could get the proper output as the following. Also, when I removed `-m` switch from my command, the table was formatted properly, though consecutive lines were not condensed into one.

```latex
\documentclass[10pt]{article}

\usepackage{tabularray}
\UseTblrLibrary{booktabs}

\begin{document}

\title{Hello}
\author{Hello}

\maketitle

\section{Table}

Hello world! Hello world!

\begin{table}[t]
  \begin{tblr}{colspec={Q[c]Q[c]Q[c]Q[c]}}
    \toprule
    aaaaaa & bbbbb & ccc & dd \\
    11 & 2  & 33 & 4          \\
    5  & 66 & 7  & 8          \\
    \bottomrule
  \end{tblr}
\end{table}

\end{document}
```

**Comment by cmhughes** [comment] 2023-03-04 20:30
Thanks for this. I can confirm the behaviour. This is not intended. 

I'll look into it and report back.

**Comment by cmhughes** [comment] 2023-03-04 20:37
I think it's the combination of the `dontMeasure` and the `-m` switch.

**Comment by tatsy** [comment] 2023-03-06 06:18
I agree with you that the bug on the `dontMeasure` feature and think other features of lookForAlignDelims work fine as far as I checked. Thank you very much for your kind help.

**Comment by cmhughes** [comment] 2023-03-15 13:17
Thanks again.

This is fixed and released as of https://github.com/cmhughes/latexindent.pl/releases/tag/V3.20.4. I'll get it uploaded to ctan next.

**Closed by cmhughes** 2023-03-15 13:17 UTC
Labels: bug, align-at-ampersand-routine

**Comment by tatsy** [comment] 2023-03-16 02:30
@cmhughes Thank you very much for your kind help! I look forward to the new release.
